### ISSUE TITLE
Feature Request: setup.py

### ISSUE THREAD

**Issue by jgarte** [bozokopic/mbgui#4]
Hi could a `setup.py` file be added for this project?

I can try to submit a PR for it when I get a chance.

**Comment by bozokopic** [comment]
setup.py is available in qt and tk branch.

in case of gtk branch (current master), implementation is based only on
C code (python is not used).

for building binaries, build.sh is available. it depends on C compiler and
gtk3 library (pkg-config is used for detection of compile/link flags).
